---
- hosts: 172.18.0.3
  tasks:
    - name: Installs services on web server
      apt: pkg=apache2 state=installed update_cache=true
      notify:
        - start apache2
      apt: pkg=nmap state=installed update_cache=true
      notify:
        - start nmap
      apt: pkg=net-tools state=installed update_cache=true
      notify:
        - start net-tools
      apt: pkg=iputils-ping state=installed update_cache=true
      notify:
        - start iputils-ping
      
      apt: pkg=vim state=installed update_cache=true
      notify:
        - start vim
      
  handlers:
    - name: start apache2
      service: name=apache2 state=started
