---
- hosts: 172.18.0.5
  tasks:
    - name: Installs services on DB server
      apt: pkg=mariadb* state=installed update_cache=true
      notify:
        - start mysql
      apt: pkg=nmap state=installed update_cache=true
      notify:
        - start nmap
      apt: pkg=net-tools state=installed update_cache=true
      notify:
        - start net-tools
      apt: pkg=iputils-ping state=installed update_cache=true
      notify:
        - start iputils-ping
      
      apt: pkg=vim state=installed update_cache=true
      notify:
        - start vim
      
  handlers:
    - name: start mysql
      service: name=mysql state=started
